
import slicer.testing

slicer.testing.exitFailure("This test is expected to fail !")

